# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ca8d15b3aa81659cd6faa56be55e2be2a508bdb1441732ce170f18461e1aa6111398d555276d8133f4dd2d8c275dc3765063ed1e1a90e6ad620ca9c2f289d9e

test:
  secret_key_base: 51e9014b0345212febfbb1c75d720c51924b7ce41a25738bfbb09ea2a978864104603a7148e6910ee5df741e810923afa9dad743f2149af8bed9a1354fb3dc03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
